dist: xenial
language: go
if: type = push
services:
- docker
script:
- mkdir -p $GOPATH/src/github.com/hashicorp && cd $_
- git clone https://github.com/hashicorp/vault.git
- cd vault
- make bootstrap
- make dev
- make test
- make bin
