dist: xenial
if: type = push
services:
- docker
script:
- bash vault.sh
- bash aws.sh
- bash docker.sh
- bash terraform.sh
deploy:
  provider: script
  script: terraform apply -auto-approve terraform.hcl
  on:
    tags: true
