dist: xenial
language: python
python:
- "3.7"
services:
- docker
if: type = push
script:
- bash vault.sh
- bash docker.sh
- bash terraform.sh
deploy:
  provider: script
  script: terraform apply -auto-approve .
